export {
  BOOK_IR_VERSION,
  isTextBlock,
  logicalLength,
  textOf,
  type BlockIR,
  type BlockStyleIR,
  type BookIR,
  type BookFontFaceIR,
  type BookFontFamilyIR,
  type BookLocator,
  type BookNavigationItem,
  type BookPosition,
  type ExternalSourceRef,
  type HeadingBlockIR,
  type ImageAssetIR,
  type ImageBlockIR,
  type InlineMark,
  type InlineRunIR,
  type InternalLinkIR,
  type InternalLinkKind,
  type NoteKind,
  type ParagraphBlockIR,
  type SectionIR,
  type Size,
  type SourceSpan,
  type TextBlockIR,
} from "./model";
export {
  BookValidationError,
  assertValidBookIR,
  validateBookIR,
  type BookValidationIssue,
  type BookValidationIssueCode,
} from "./validate";
