packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@shopify/react-native-skia"
  - esbuild

patchedDependencies:
  "@expo/ui@57.0.10": patches/@expo__ui@57.0.10.patch
  "@shopify/react-native-skia@2.6.2": patches/@shopify__react-native-skia@2.6.2.patch
