plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'dev.chihum.persimmon'
version = '0.1.0'

android {
  namespace 'dev.chihum.persimmon.googleauthorization'

  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-auth:21.6.0'
}
